version: '2'
services:
    angularpoc-app:
        image: angularpoc
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://angularpoc-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=angularpoc
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    angularpoc-mongodb:
        extends:
            file: mongodb.yml
            service: angularpoc-mongodb
